feat: auth func for ethereum
ceramicnetwork/js-3id-blockchain-utils pull request #10
Opened 2020-04-24 15:39 UTC by zachferland

Auth functions go here, but actual auth providers are in 3id-connect, the idea being most implemented auth providers can pull in a shared auth function for their network from here, but custom implementations can still be passed in authProviders 

Open:
[] could use a good way to export auth functions, but no reason they have to be able to resolve based on type/chain etc like validation proofs 
[] expect these to be general to each network and their provider/wallet interfaces, and anything specific implemented in authProvider instead, but maybe there is reason to have more than 1 per network

2020-05-14 06:57 UTC, oed reviewed
Looks like the function also needs to be exported in index.js. Any other blockers here before merging?

2020-05-29 20:16 UTC, zachferland commented
Exports auth functions by network name ie 
```
import { createLink, authenticate } from '3id-blockchain-utils'

authenticate.ethereum(message, accountId, provider)
```
cc @oed

2020-05-29 20:43 UTC, oed requested changes

2020-05-29 20:43 UTC, oed commented on README.md
> +await authenticate.ethereum(message, '0x123abc...', ethereumProvider)
This api seems wrong. We should be able to have a generic authenticate function in the same way as `createLink` and `validateLink` are generic. The `createLink` function uses a type detector, we should be able to use that. This also aligns us well to the update to CAIP-10 where we can just detect the auth function from the accountId.

2020-05-30 16:38 UTC, merged